# Generated by Django 4.1.2 on 2022-10-12 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSummit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('high', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Genre',
            new_name='Country',
        ),
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.AddField(
            model_name='aboutsummit',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summit.country'),
        ),
    ]
