# Generated by Django 4.0.2 on 2022-12-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0003_mountainrange_aboutsummit_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsummit',
            name='lat_pos',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='aboutsummit',
            name='long_pos',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
