# Generated by Django 4.0.2 on 2022-12-23 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsummit',
            name='image_prev',
            field=models.FileField(default='mountain-default', upload_to='images/'),
        ),
        migrations.CreateModel(
            name='MountainImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('aboutsummit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='summit.aboutsummit')),
            ],
        ),
    ]
