# Generated by Django 4.0.2 on 2022-12-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0006_aboutsummit_image_prev_mountainimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsummit',
            name='image_prev',
            field=models.FileField(default='mountain-default.jpg', upload_to='images/'),
        ),
    ]
