# Generated by Django 4.0.2 on 2023-01-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0007_alter_aboutsummit_image_prev'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsummit',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
