# Generated by Django 4.0.2 on 2023-01-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0008_aboutsummit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsummit',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='aboutsummit',
            name='title',
            field=models.CharField(default=None, max_length=200, verbose_name='Name of mountain'),
        ),
    ]
