# Generated by Django 4.0.2 on 2023-01-23 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0009_alter_aboutsummit_slug_alter_aboutsummit_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsummit',
            name='country_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_second', to='summit.country', verbose_name='Second country'),
        ),
        migrations.AlterField(
            model_name='aboutsummit',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summit.country', verbose_name='First Country'),
        ),
        migrations.AlterField(
            model_name='aboutsummit',
            name='image_prev',
            field=models.FileField(default='mountain-default.jpg', upload_to='images/prev/%Y-%m-%d/'),
        ),
    ]
