# Generated by Django 4.0.2 on 2023-01-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0013_country_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='URL'),
        ),
    ]
