# Generated by Django 4.0.2 on 2023-01-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0014_country_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image_country',
            field=models.ImageField(default='default_flag.jpg', upload_to='country_image'),
        ),
    ]
