# Generated by Django 4.0.2 on 2023-01-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0015_country_image_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='image_country',
            field=models.ImageField(default='default_country.jpg', upload_to='country_image'),
        ),
    ]
