# Generated by Django 4.0.2 on 2023-01-27 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit', '0016_alter_country_image_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsummit',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_first', to='summit.country', verbose_name='First Country'),
        ),
    ]
